### ISSUE TITLE
Can not compile 

### ISSUE THREAD

**Issue by pavel-esir** [valbok/snu#1]
When I am trying to compile after running cmake . it shows Warning

CMake Warning (dev) at CMakeLists.txt:24 (add_subdirectory):
  The source directory
    /home/pavel/projects/snu/lib/enki
  does not contain a CMakeLists.txt file. 
...
and then shows Error 

-- Configuring done 
CMake Error at viewer/CMakeLists.txt:41 (add_library):
 Cannot find source file: /home/pavel/projects/snu/lib/enki/viewer/EPuckModel.cpp

How this problem could be solved?

**Comment by valbok** [comment]
Hi,
lib/enki is a submodule that should be cloned separately.

```
$ git submodule update --init --recursive
```

and after that

```
snu/ $ cmake .
snu/ $ make
```

**Comment by valbok** [comment]
Updated readme
